"""empty message

Revision ID: add_currency_rates_1
Revises: add_user_1
Create Date: 2025-03-21 22:11:49.422916+03:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "add_currency_rates_1"
down_revision = "add_user_1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency_rates",
        sa.Column("from_currency", sa.String(length=8), nullable=False),
        sa.Column("to_currency", sa.String(length=8), nullable=False),
        sa.Column("provider", sa.String(length=4), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("from_currency", "to_currency", "provider", "date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("currency_rates")
    # ### end Alembic commands ###
