"""empty message

Revision ID: add_portfolios_2
Revises: add_portfolios_1
Create Date: 2025-03-22 19:40:48.710626+03:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "add_portfolios_2"
down_revision = "add_portfolios_1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("portfolios", sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("portfolios", "is_active")
    # ### end Alembic commands ###
