"""empty message

Revision ID: add_cache_1
Revises:
Create Date: 2025-03-16 00:38:52.005417+03:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "add_cache_1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", postgresql.BYTEA(), server_default=sa.text("NULL"), nullable=True),
        sa.Column("ttl", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key"),
        prefixes=["UNLOGGED"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cache")
    # ### end Alembic commands ###
